[metadata]
creation_date = "2023/01/11"
integration = ["endpoint"]
maturity = "production"
updated_date = "2025/02/14"

[rule]
author = ["Elastic"]
description = """
Detects Inter-Process Communication with Outlook via Component Object Model from an unusual process. Adversaries may
target user email to collect sensitive information or send email on their behalf via API.
"""
from = "now-9m"

language = "eql"
license = "Elastic License v2"
name = "Suspicious Inter-Process Communication via Outlook"
risk_score = 47
rule_id = "Q1dee0500-4aeb-44ca-b24b-4a285d7b6ba1"
severity = "medium"
type = "eql"

query = '''
sequence with maxspan=1m
[process where host.os.type == "windows" and event.action == "start" and
  (
    process.name : (
      "rundll32.exe", "mshta.exe", "powershell.exe", "pwsh.exe",
      "cmd.exe", "regsvr32.exe", "cscript.exe", "wscript.exe"
    ) or
    (
      (process.code_signature.trusted == false or process.code_signature.exists == false) and
      (process.Ext.relative_file_creation_time <= 500 or process.Ext.relative_file_name_modify_time <= 500)
    )
  )
] by process.entity_id
[process where host.os.type == "windows" and event.action == "start" and process.name : "OUTLOOK.EXE" and
  process.Ext.effective_parent.name != null] by process.Ext.effective_parent.entity_id
'''


